ALTER TABLE farmer_profiles
  ADD COLUMN IF NOT EXISTS supplier_type VARCHAR(30) NOT NULL DEFAULT 'FARMER',
  ADD COLUMN IF NOT EXISTS number_of_farms INTEGER NULL;

ALTER TABLE pickup_requests
  ADD COLUMN IF NOT EXISTS receipt_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS receipt_file_name VARCHAR(255) NULL;
